# Generated by Django 5.1.6 on 2025-02-25 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('platform', models.CharField(max_length=50)),
                ('genre', models.CharField(max_length=50)),
                ('available', models.BooleanField(default=True)),
            ],
        ),
    ]
