# Generated by Django 5.1.6 on 2025-04-15 00:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_userprofile_google_id'),
        ('catalog', '0007_game_description'),
    ]

    operations = [
    ]
