# Generated by Django 5.1.6 on 2025-04-29 21:30

import catalog.storage_backends
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0008_merge_20250415_0028'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='image',
            field=models.ImageField(blank=True, default='items/default_game_image.png', null=True, storage=catalog.storage_backends.CatalogMediaStorage(), upload_to='items/'),
        ),
    ]
