# Generated by Django 5.1.6 on 2025-04-29 23:31

import catalog.storage_backends
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0009_game_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='image',
            field=models.ImageField(blank=True, default='items/default_game_image.png', null=True, storage=catalog.storage_backends.CatalogMediaStorage(), upload_to=''),
        ),
    ]
